CREATE DATABASE   mydb2; 
USE mydb2;
## Intro : In this Project we are going to clean the data using SQL IN MYSQL Workbench
## The date contains the details of  housing sales  from some states  in USA

SELECT * FROM NEW_RECORD ;

## IN the first we are going to find the duplicate values and going to remove it

WITH ROWNUMCTE AS
(SELECT *, ROW_NUMBER()OVER
(partition by  PARCELID, LANDUSE, PROPERTYADDRESS, SALEDATE,LEGALREFERENCE 
ORDER BY UNIQUEID) ROW_NUM FROM NEW_RECORD)

SELECT * FROM ROWNUMCTE
WHERE ROW_NUM <2
ORDER BY PARCELID;

 
## BREAKING CITY ADDRESS INTO INDIVIDUAL COLUMNS

SELECT PROPERTYADDRESS FROM NEW_RECORD;

SELECT SUBSTRING_INDEX(PROPERTYADDRESS,',',1) AS ADRESS,
SUBSTRING_INDEX(PROPERTYADDRESS,',',-1) AS ADRESS  FROM NEW_RECORD;

ALTER TABLE NEW_RECORD
ADD ADDRESS varchar (255);
SET SQL_SAFE_UPDATES =0;
UPDATE NEW_RECORD
SET ADDRESS = SUBSTRING_INDEX(PROPERTYADDRESS,',',1);

ALTER TABLE NEW_RECORD
ADD CITY varchar (255);
SET SQL_SAFE_UPDATES =0;
UPDATE NEW_RECORD
SET CITY = SUBSTRING_INDEX(PROPERTYADDRESS,',',-1);

SELECT * FROM NEW_RECORD;

# Breaking  Owners ADDRESS into Invidiual Columns

SELECT OWNERADDRESS,
SUBSTRING_INDEX(OWNERADDRESS,',',1) AS A,
SUBSTRING_INDEX(OWNERADDRESS,',',-1) AS B, 
SUBSTRING_INDEX(SUBSTRING_INDEX(OWNERADDRESS,',',2), ',', -1)AS C FROM NEW_RECORD;

ALTER TABLE NEW_RECORD
ADD OWNER_ADDRESS varchar (255);
SET SQL_SAFE_UPDATES =0;
UPDATE NEW_RECORD
SET OWNER_ADDRESS = SUBSTRING_INDEX(OWNERADDRESS,',',1);


ALTER TABLE NEW_RECORD
ADD OWNER_STATE varchar (255);
SET SQL_SAFE_UPDATES =0;
UPDATE NEW_RECORD
SET OWNER_STATE = SUBSTRING_INDEX(OWNERADDRESS,',',-1);


ALTER TABLE NEW_RECORD
ADD OWNER_CITY varchar (255);
SET SQL_SAFE_UPDATES =0;
UPDATE NEW_RECORD
SET OWNER_CITY = SUBSTRING_INDEX(SUBSTRING_INDEX(OWNERADDRESS,',',2), ',', -1);

SELECT * FROM NEW_RECORD;


#CHANGING  Y & N  From SOLD AS VACANT AS YES AND NO

SELECT DISTINCT (SOLDASVACANT) FROM NEW_RECORD;

SELECT DISTINCT SOLDASVACANT, CASE
 WHEN SOLDASVACANT = 'Y' THEN 'YES'
 WHEN SOLDASVACANT = 'N' THEN 'NO'
 ELSE SOLDASVACANT
 END FROM NEW_RECORD;
 
 UPDATE NEW_RECORD
 SET SOLDASVACANT = CASE
 WHEN SOLDASVACANT = 'Y' THEN 'YES'
 WHEN SOLDASVACANT = 'N' THEN 'NO'
 ELSE SOLDASVACANT
 END;
 
 SELECT DISTINCT SOLDASVACANT FROM NEW_RECORD;
 
 
##DROPING UNWANTED COLUMNS

SELECT * FROM NEW_RECORD;

ALTER TABLE NEW_RECORD
DROP COLUMN OWNERADDRESS,DROP COLUMN  PROPERTYADDRESS,DROP COLUMN  TAXDISTRICT;
